AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Function - VPC

Parameters:

  VpcSubnetIdList:
    Description: Private VpcSubnets for Serverless Functions
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: Must be the identifier of an existing Subnets

  VpcSecurityGroupIdList:
    Description: Security Group List for Serverless Functions
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: Must be the identifier of existing SecurityGroups


Resources:

  ServerlessFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: "serverless-function-basic-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      #FunctionName: ""
      Description: "Serverless Function"
      Handler: index.handler
      Runtime: python3.9
      #CodeUri: 's3://testBucket/mySourceCode.zip'
      InlineCode: |
        def handler(event, context):
          print("Application Version 3.0!")
          return "3.0"
      Tracing: Active
      Timeout: 120
      MemorySize: 128
      PropagateTags: true
      Role: !GetAtt ServerlessFunctionExecutionRole.Arn  #serverless-function-basic-ServerlessFunctionRole-13GA0O9DQ5JJV
      AutoPublishAlias: "live"
      AutoPublishAliasAllProperties: false
      VersionDescription: "3.0"
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
              Resource: '*'
      Environment:
        Variables:
          DatabaseName: sonic
          DatabaseUser: mac2
      EphemeralStorage:
        Size: 512
      VpcConfig:
        SecurityGroupIds: !Ref VpcSecurityGroupIdList
        SubnetIds: !Ref VpcSubnetIdList
      Tags:
        Name: "serverless-function-basic"

  ServerlessFunctionLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServerlessFunction}"
      RetentionInDays: 1
      
Outputs:

  ServerlessFunction:
    Value: !GetAtt ServerlessFunction.Arn



