AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Table - Basic

Resources:

  ServerlessFunction:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: "serverless-simpletable-basic"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      PrimaryKey:
        Type: String
        Name: Code
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:   
        SSEEnabled: false #If disabled (false) or not specified, server-side encryption is set to AWS owned key.
      Tags:
        Name: "serverless-simpletable-basic"




